### ISSUE TITLE
64 bit windows build probably isn't IA64

### ISSUE THREAD

**Issue by rpavlik** [wavedrom/wavedrom.github.io#15]
There's an "ia32" and "ia64" windows build listed, and while x86 is sometimes called ia32, ia64 is Itanium, not x86_64, and I highly doubt you actually built for Itanium :stuck_out_tongue_winking_eye: (If you did, I'm some mixture of impressed and horrified, please disregard this issue).  If you want a condensed way to refer to the arch, x64 is pretty commonly used (but don't use x32 in contrast, since that's using 32-bit pointers on an x86_64 cpu in long mode, an experimental ABI available in some operating systems but not supported by Windows at all).

Minor issue, I know, but figured I could prevent confusion and/or crushed dreams of Itanium users.

**Comment by drom** [comment]
@rpavlik yes, agree. `ia64` sounds weird :alien:
How about `-osx-x64-` and `-win-x64-` ?
