### ISSUE TITLE
Dis-functional export SVG/PNG when UNICODE chars are present.

### ISSUE THREAD

**Issue by drom** [wavedrom/wavedrom.github.io#17]
Added UNICODE character into WaveJSON.
Try Export SVG/PNG.
Getting error:

```
Uncaught InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

**Comment by drom** [comment]
Originally reported here: https://github.com/drom/wavedrom/issues/137

**Comment by drom** [comment]
escape libraries:
https://github.com/mathiasbynens/jsesc - ES6 (const, let)

**Comment by alexwhittemore** [comment]
Oh good, I'm not the only one :)

I was wondering why it kept exporting 0kb PNGs

**Comment by udif** [comment]
Will this help?
#23

**Comment by drom** [comment]
Thanks for the help. Please try v1.4.2
https://github.com/wavedrom/wavedrom.github.io/releases/tag/v1.4.2
