### ISSUE TITLE
v1.4.0 win-64 fails to launch

### ISSUE THREAD

**Issue by alexwhittemore** [wavedrom/wavedrom.github.io#21]
Unfortunately, I don't have much in the way of practical info to give without instruction on how to collect an error report. But on my Windows 10 system, V1.4.0 win-64 fails to launch, where 1.3.1 win-ia64 seems to work just fine.

**Comment by drom** [comment]
Yes, I can reproduce the issue.

**Comment by drom** [comment]
@alexwhittemore please try v1.4.1 it fixes the issue for me.

**Comment by alexwhittemore** [comment]
Confirmed, works. Thanks!

What was the bug? It looks like you only changed a few minor configuration things since then?

**Comment by drom** [comment]
It was bug in nwjs v0.18.0 looks like. And I am using v0.18.5 now.
