### ISSUE TITLE
V1.4.1 doesn't work for MacOSX 11.10.6

### ISSUE THREAD

**Issue by SteffenReith** [wavedrom/wavedrom.github.io#22]
Hi,

downloading wavedrom-editor-v1.4.1-os64 provides a non working binary. The nwjs.app application quits with "You can't open the application "nwjs" because it may be damaged or incomplete".  The "wavedrom-editor"
in "wavedrom-editor-v1.4.1-osx-x64/nwjs.app/Contents/MacOS" is not executable (missing chmod +x). Making it executable results in a plain NW.JS-window.

**Comment by thomasrussellmurphy** [comment]
I can replicate this in MacOS Version 10.11.6. Can the v1.4.1 `osx` release be marked as bad in the release notes? Should this remain an open issue?

v1.4.2 works, but "it is from an unidentified developer," failing the MacOS GateKeeper signed software check.

**Comment by drom** [comment]
Closing for now. Updated v1.4.2 release notes.
Please open "it is from an unidentified developer" issue is needed.
