### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by Bamban** [wavedrom/wavedrom.github.io#38]
Hi ! First of all thanks a lot for this awesome tool.
I'm using it to generate waveforms for some documentation. I currently have some json wave files in a directory. In order to process them with latex, I need pdf. I can easily go from svg to pdf (which is great because everything is vector) with inkscape. The only thing I can't automate is the export of json to svg. I currently open the editor and click "export svg".

Hence my question : would it be possible to imagine a command line interface doing something like this ?
`./wavedrom --in wave.json --export-svg --out wave.svg`

Thanks for your time !

**Comment by wysman** [comment]
I am waiting this feature to be able to create svg for documentations

**Comment by drom** [comment]
I have created CLI version of wavedrom here: https://github.com/wavedrom/wavedrom/releases/tag/v2.1.2

For help:

```
node wavedrom.js --help
```

To generate SVG file from JSON5 file.

```
node wavedrom.js -i mysignal.json5 > mysignal.svg
```
Please try.

**Comment by yunqu** [comment]
In general these command line interfaces work fine. I have tested on armhf and aarch64. The main concern is the performance; suppose we have a long waveform the render, it can takes 6 seconds to render something like:

```python
clock = {'signal': [{'name': 'clock_0', 'wave': 'hlhlhlhlhlhlhlhl'*20}]*4,
                 'foot': {'tock': 1},
                 'head': {'text': 'Clock Signal'}}
```

This is only 320 samples with 4 channels. I did some extensive tests; it may take 15 seconds to render 1000 samples.

**Comment by drom** [comment]
wavedrom was not designed for the rendering of long simulation traces.
I have started another project for that https://github.com/wavedrom/zoom

**Comment by yunqu** [comment]
@drom  This is awesome. Do you have any example/ instructions on how to use zoom?
