### ISSUE TITLE
Command-line use

### ISSUE THREAD

**Issue by nrclark** [wavedrom/wavedrom.github.io#4]
We all love wavedrom at my office, and we draw a lot of diagrams with it!

Is there any chance we could get a slight modification to the NW application so that it can be used without a display server?

Runnning ``./WavedromEditor source (infile) svg (outfile)`` works pretty well when we're at our desks, but our build servers can't do it because they don't have an active X11 display. WavedromEditor appears to need a working display so that it can pop up a little momentary window while it works.

This issue can be shown by running  ``DISPLAY="" ./WavedromEditor source (infile) svg (outfile)`` on a unixlike machine, or by doing ``./WavedromEditor source (infile) svg (outfile)`` over SSH with X11 forwarding turned off.

Older versions of the NW app (such as WaveDrom_20130413.nw) seem to work OK in headless mode, but we'd love to be able to use the latest-greatest!

**Comment by drom** [comment]
I am working to make wavedrom headless, but looks like node-webkit requires X11, and I don't know any workarounds by now.

**Comment by drom** [comment]
Please use https://github.com/wavedrom/cli for the headless CLI version of WaveDrom.
