### ISSUE TITLE
Do not refresh to the starting position when modifying the waveform.

### ISSUE THREAD

**Issue by bitrocco** [wavedrom/wavedrom.github.io#40]
### Do not refresh to the starting position when modifying the waveform.

Reference #125 
> For larger waveforms that extend past the edges of the window, the scroll position resets to the top left each time a change is made to the source and render is performed. It would be nice if the scroll position did not reset. When modifying the large waveforms it is convenient to look at the render as you enter source, but having it jump back to the top left each time makes this a pain.

I also encountered this problem, I hope can optimize as soon as possible. Sincerely hope !!

**Comment by drom** [comment]
@bitrocco @nockieboy I have fixed an issue, please try online and I will update desktop App if it works as expected.

**Comment by bitrocco** [comment]
@drom  Thank you very much for your update, it works perfectly !

**Comment by nockieboy** [comment]
Yes, works perfectly now - thanks for the quick update!
