### ISSUE TITLE
editor crashes

### ISSUE THREAD

**Issue by parafux** [wavedrom/wavedrom.github.io#49]
I try to edit the following code with the online editor or the downloaded software editor.

if i change i++ to i+1 or i+ or anything else, that was a mistypo. then the editor crashes. a reload does not help, because the cache is still full with the errornous code.

The downloaded software cannot be started again, because the errornous code is still in the cache, so propably i have to delete any init file or reinstall the software.

Seems to be an issue with an endless loop, that temporary exists in my code, but that i did not really want to be translated.

But even if i coded a bug, the tool should not hang up.

(function (bits, ticks) {
  var i, t, gray, state, data = [], arr = [];
  for (i = 0; i < bits; i++) {
    arr.push({name: i + '', wave: ''});
    state = 1;
    for (t = 0; t < ticks; t++) {
      data.push(t + '');
      gray = (((t >> 1) ^ t) >> i) & 1;
      arr[i].wave += (gray === state) ? '.' : gray + '';
      state = gray;
    }
  }
  arr.unshift('gray');
  return {signal: [
    {name: 'bin', wave: '='.repeat(ticks), data: data}, arr
  ]};
})(5, 16)

**Comment by drom** [comment]
I have fixed WebApp to store source code only after execution to avoid infinite loops.

To clear browser cache: [click here](https://wavedrom.com/editor.html?%7B%20%22signal%22%20%3A%20%5B%0A%20%20%7B%20%22name%22%3A%20%22clk%22%2C%20%20%22wave%22%3A%20%22P......%22%20%7D%2C%0A%20%20%7B%20%22name%22%3A%20%22bus%22%2C%20%20%22wave%22%3A%20%22x.%3D%3D.%3Dx%22%2C%20%22data%22%3A%20%5B%22head%22%2C%20%22body%22%2C%20%22tail%22%2C%20%22data%22%5D%20%7D%2C%0A%20%20%7B%20%22name%22%3A%20%22wire%22%2C%20%22wave%22%3A%20%220.1..0.%22%20%7D%0A%5D%7D%0A)

To clear Desktop App cache look here:
http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-user-data-dir

**Comment by parafux** [comment]
perfect, that helps for using the web-interface.
also the cache for the desktop app could be cleared now:
C:\Users\<my-name>\AppData\Local\WaveDromEditor\User Data

**Comment by parafux** [comment]
Could you please do the changes, you have done on the WebApp also for the DesktopApp and the PortableApp?

**Comment by drom** [comment]
v2.1.6 release includes this fix.
https://github.com/wavedrom/wavedrom.github.io/releases/tag/v2.1.6
