### ISSUE TITLE
add version number into the menu

### ISSUE THREAD

**Issue by drom** [wavedrom/wavedrom.github.io#51]

**Comment by Nicolas-Mariotti** [comment]
Isn't this already done [here](https://github.com/wavedrom/wavedrom.github.io/commit/08fbb5aaffe9839721fd714663826430d1359c2c) ?

**Comment by drom** [comment]
Yes. it is done https://github.com/wavedrom/wavedrom.github.io/commit/08fbb5aaffe9839721fd714663826430d1359c2c
