### ISSUE TITLE
OSX command line mode

### ISSUE THREAD

**Issue by mrvkino** [wavedrom/wavedrom.github.io#6]
Hi,

I tried the v 0.10.0 and I run into problem on osx. By the way, the way I was able to run the wavedrom command line on osx is by typing the following command:
> open ./WaveDromEditor.app --args source "input.json" [png/svg] "output_image"

The linux command does not work for me on osx.

When I run wavedrom on the CLI, it opens a window editor and get stuck on it (even for the simplest input file). The only way I can have my image is by using the opened gui, exporting the image and then closing the window by hand. If I use the v 0.9.13 it works perfectly.

For the following command:
> open ./WaveDromEditor.app --args source simple_mywave.wjson svg simple_mywave.svg

With the following code in simple_mywave.wjson:
>{signal: [
>  {name: 'clk', wave: 'p.....|...'},
>  {name: 'rst', wave: '10....|...'},
>  {name: 'dat', wave: 'x.345x|=.x', data: ['test', 'body', 'tail', 'data']},
>  {name: 'req', wave: '0.1..0|1.0'},
>  {},
>  {name: 'ack', wave: '1.....|01.'},
>]}

I get this window instead of my output image:
![image](https://cloud.githubusercontent.com/assets/279511/6993630/4704ba48-dac8-11e4-9c5a-b0399505f283.png)

**Comment by drom** [comment]
could you try v0.11.2?

**Comment by mrvkino** [comment]
Still does the same behaviour.

**Comment by drom** [comment]
Please try v0.11.4

**Comment by mrvkino** [comment]
Great! The files are created and the window closes.

By the way, do you think it would be possible to launch wavedrom from the command line without having a window popping briefly (like a regular command-line). Not a big deal, but still it would be appreciated.

Thanks for your great work!
