### ISSUE TITLE
Exporting SVG and PNG still not working properly

### ISSUE THREAD

**Issue by JBDavisson** [wavedrom/wavedrom.github.io#8]
I'm using WaveDrom on Win 8 64 and the standalone program will just not export PNG/SVG files for me. I had one successful export, and then had to add a few more waves to it, after which it wont export. 

I have likewise tried to use the online editor, which will appear to save, though it saves a 0 byte file.

I've even downloaded the 32-bit version for windows (linked from a forum post that Drom said he had fixed the exporting issue) but I just get an error message in the program when I try to export PNG.

This is such a cool program, and I was hoping sincerely to take my Digital Logic Design class' lab reports over the top with it! I'm not sure it'll work for me if it wont export though :(

**Comment by drom** [comment]
Hey @JBDavisson can you tell me exact versions of WaveDrom standalone and the browser name/version that you are using?

**Comment by JBDavisson** [comment]
Hi!


wavedrom-editor-v0.11.4-win-ia64<https://github.com/wavedrom/wavedrom.github.io/releases/download/v0.11.4/wavedrom-editor-v0.11.4-win-ia64.zip> is the version of the standalone that I'm using and I'm using Google Chrome Version 45.0.2454.85 m?.


The editor has no unexpected behavior until attempting to export to SVG or PNG. It's truly a brilliant piece of software, just a bit frustrating in this one issue. I have attached a screenshot of an error message that I'm getting when trying to export PNG.


If there is anything else I can provide to assist with this, let me know!


Respectfully,


JBDavisson


________________________________

**Comment by drom** [comment]
let me find Win8  and test it.

**Comment by JBDavisson** [comment]
I don't mind testing it when I get home here in just a few minutes.
________________________________________

**Comment by drom** [comment]
Here is my test results:

os \ brwsr                 | Cr43 | Cr44 | Cr45 | FF40
-------------------------- | ------- | ------ | ------- | ------
Linux - x64 - svg      |           | :+1:  |          | :+1:
Linux - x64 - png      |           | :+1:  |          | 0
Win7pro - x64 - svg | :+1:    |         |  :+1:  | :+1:
Win7pro - x64 - png | :+1:   |          | :+1:  | 0

**Comment by drom** [comment]
@JBDavisson have you tried v1.2.0 ?

**Comment by JBDavisson** [comment]
?I have, and apologize for not responding sooner. I'm not sure what the issue was previously, when I first tried wavedrom again after my initial problem, but it exports images appropriately now. Thanks for all of your hard work on Wavedrom, it's a really great way for me to make timing diagrams.

________________________________

**Comment by drom** [comment]
@JBDavisson thank you for using WaveDrom.
